### ISSUE TITLE
LCD background issue

### ISSUE THREAD

**Issue by basic2004** [jcmoyer/Nuked-SC55#7]
![image](https://github.com/jcmoyer/Nuked-SC55/assets/24873576/a277e2d0-9631-4072-a446-42531bbeb495)

I built your latest revision ([0e7768a](https://github.com/jcmoyer/Nuked-SC55/commit/0e7768ab8a806095ca819cbec8aa508e54327a34)) but LCD background is showing black. (except JV880... showing correctly)

I built these compilers but both are same issue.
MSVC 14.40.33807
GCC 14.1.0

OS : Windows 10.0.19045.4598 (64bit)

**Comment by jcmoyer** [comment]
Hi,

This is because the emulator cannot find `back.data`. This file needs to either be in the same directory as the executable *or* in `../share/nuked-sc55` directory. You can run `cmake --install . --prefix=<dir>` to produce a complete distribution at `<dir>` with all the files in the correct place.

**Comment by AndyGraewe** [comment]
When I copied the rom files to subdirectory and add a parameter to the path, I have this black LED issue.
But only for mk2 roms, when they are in a different folder then the binary.
But, when I put the back.data file in the mk2 rom subfolder, it works fine.

Interesting is that I dont have this issue when putting mk1, sc155 or jv880 roms in subfolders.

**Comment by jcmoyer** [comment]
@AndyGraewe The current behavior is somewhat confusing because nuked-sc55 wants to look in two places for resources and it's not documented. When the emulator starts it looks for (relative to the executable) `../share/nuked-sc55` and if it exists, that is where it will load `back.data` from. Otherwise, it uses the directory of the executable. Note that this is **not** the current working directory. 

After `cmake --build`, the executable directory won't have the LCD background in it, and it won't have a `share` directory up the filesystem. This is why I recommend running `cmake --install` to generate the correct directory layout for you.

Note that upstream works around this problem by always copying back.data to the build directory. This works if you only ever plan to run the emulator from where you built it, but otherwise you will need to run `cmake --install`.
